name: deploy-to-glitch
# run-name: ${{ github.actor }} is learning GitHub Actions
run-name: Pushing to glitch
on: 
  push:
    tags:
      - '*'
jobs:
  push-to-glitch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # - name: Pushes to another repository
      #   uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source-directory: .
      #     destination-github-username: 'cpina'
      #     destination-repository-name: 'pandoc-test-output'
      #     user-email: carles3@pina.cat
      #     target-branch: main
      - name: GIT commit and push all changed files
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "CBEngineer9@users.noreply.github.com"
          git config push.default upstream
          # git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git remote add glitch ${{ secrets.GLITCH_REPO }}
          git push glitch main